CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"display_name" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"avatar_url" text,
	"role" text DEFAULT 'user',
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "story_workspace_workspaces" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"owner_id" bigint NOT NULL,
	"settings" text DEFAULT '{}',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "story_workspace_stories" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"review_status" text DEFAULT 'pending' NOT NULL,
	"type" text DEFAULT 'short' NOT NULL,
	"content" text,
	"author_id" bigint NOT NULL,
	"workspace_id" text NOT NULL,
	"character_count" integer DEFAULT 0 NOT NULL,
	"scene_count" integer DEFAULT 0 NOT NULL,
	"agent_generated" integer DEFAULT 1 NOT NULL,
	"agent_session_id" text,
	"review_notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"confirmed_at" timestamp with time zone,
	"published_at" timestamp with time zone,
	CONSTRAINT "story_workspace_stories_status_check" CHECK ("story_workspace_stories"."status" IN ('draft', 'published', 'archived')),
	CONSTRAINT "story_workspace_stories_review_status_check" CHECK ("story_workspace_stories"."review_status" IN ('pending', 'confirmed', 'rejected')),
	CONSTRAINT "story_workspace_stories_type_check" CHECK ("story_workspace_stories"."type" IN ('short', 'long', 'script', 'outline')),
	CONSTRAINT "story_workspace_stories_agent_generated_check" CHECK ("story_workspace_stories"."agent_generated" IN (0, 1))
);
--> statement-breakpoint
ALTER TABLE "story_workspace_workspaces" ADD CONSTRAINT "story_workspace_workspaces_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "story_workspace_stories" ADD CONSTRAINT "story_workspace_stories_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "story_workspace_stories" ADD CONSTRAINT "story_workspace_stories_workspace_id_story_workspace_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."story_workspace_workspaces"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_unique" ON "users" USING btree ("email");
--> statement-breakpoint
CREATE INDEX "idx_sw_workspaces_owner" ON "story_workspace_workspaces" USING btree ("owner_id");
--> statement-breakpoint
CREATE INDEX "idx_sw_stories_author" ON "story_workspace_stories" USING btree ("author_id", "updated_at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX "idx_sw_stories_review_status" ON "story_workspace_stories" USING btree ("review_status", "updated_at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX "idx_sw_stories_status" ON "story_workspace_stories" USING btree ("status", "updated_at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX "idx_sw_stories_type" ON "story_workspace_stories" USING btree ("type", "updated_at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX "idx_sw_stories_search" ON "story_workspace_stories" USING btree ("title");
--> statement-breakpoint
CREATE INDEX "idx_sw_stories_agent" ON "story_workspace_stories" USING btree ("agent_session_id");
--> statement-breakpoint
COMMENT ON TABLE "users" IS
  'Canonical platform users for ink-memory. Admin responses must never expose password_hash.';
--> statement-breakpoint
COMMENT ON TABLE "story_workspace_workspaces" IS
  'Canonical Story workspaces owned by users in the same PostgreSQL database.';
--> statement-breakpoint
COMMENT ON TABLE "story_workspace_stories" IS
  'Canonical Story records belonging to a workspace and author in the same PostgreSQL database.';
