// [Input] Runner-owned loopback PostgreSQL, Registry101 Repository/Receipt code and normalized import fixtures.
// [Output] Atomic owner, replay, concurrency, timestamp, rollback, recovery and first-login evidence.
// [Pos] Provider-free local-data UOW contract; it never connects to configured application databases.
// [Sync] 2026-09-15: prove the current schema needs no migration for the two OAuth business operations.
import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { firstLoginCompleteOutputDto, localDataImportInputDto, localDataImportOutputDto, type LocalDataImportInput } from "../../app/lib/dream/localDataImportDto";
import { LocalDataImportRepository } from "../../app/lib/dream/localDataImportRepository";
import { ReceiptRepository } from "../../app/lib/dream/receipts";
import { startEmbeddedPostgres, type RunningEmbeddedPostgres } from "../../packages/db/src/embedded-postgres";

async function availablePort() {
  const server = createServer();
  await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(0, "127.0.0.1", resolve); });
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("Unable to reserve isolated port");
  await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
  return address.port;
}
async function expectFailure(action: () => Promise<unknown>, code?: string) {
  try { await action(); } catch (error) {
    if (!code || (error && typeof error === "object" && "code" in error && error.code === code)) return;
    throw error;
  }
  throw new Error(`Expected failure${code ? ` ${code}` : ""}`);
}

const suffix = randomBytes(6).toString("hex"), database = `ink_auth_data_codex_test_local_import_${suffix}`;
const ownedRoot = await mkdtemp(join(tmpdir(), "ink-auth-data-local-import-"));
let embedded: RunningEmbeddedPostgres | undefined, evidence: Record<string, unknown> | undefined;

try {
  embedded = await startEmbeddedPostgres({
    mode: "embedded-postgres", dataDir: join(ownedRoot, "postgres"), port: await availablePort(), user: "postgres",
    password: `pg_${randomBytes(24).toString("base64url")}`, database, sharedBuffers: "24MB", maxConnections: 12,
  }, { listenAddresses: "127.0.0.1" });
  const setup = new pg.Client({ connectionString: embedded.connectionString });
  let pool: pg.Pool | undefined;
  await setup.connect();
  try {
    const topology = await setup.query("SELECT current_database() AS database, host(inet_server_addr()) AS address, current_setting('listen_addresses') AS listen");
    assert.deepEqual(topology.rows[0], { database, address: "127.0.0.1", listen: "127.0.0.1" });
    await setup.query(`
      CREATE SCHEMA dream;
      CREATE TABLE users (id bigint PRIMARY KEY);
      CREATE TABLE user_sessions (
        id text PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), name text, editor_state_json text NOT NULL,
        labels text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now()
      );
      CREATE TABLE daily_pictures (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id),
        date text NOT NULL, image_base64 text NOT NULL, prompt text, thumbnail_base64 text, created_at timestamptz DEFAULT now()
      );
      CREATE TABLE user_preferences (
        user_id bigint PRIMARY KEY REFERENCES users(id), voice_configs_json text, meta_prompt text, state_config_json text,
        selected_state text, timezone text, first_login_completed integer DEFAULT 0, system_config_json text, updated_at timestamptz DEFAULT now()
      );
      CREATE TABLE analysis_reports (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), report_type text NOT NULL,
        report_data_json text NOT NULL, all_notes_text text, reflection_task_id text, created_at timestamptz DEFAULT now()
      );
      CREATE TABLE dream.operation_receipts (
        service_client_id text NOT NULL, actor text NOT NULL, operation text NOT NULL, request_id text NOT NULL,
        input_sha256 text NOT NULL CHECK (input_sha256 ~ '^[0-9a-f]{64}$'), result jsonb NOT NULL, committed_at timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY (service_client_id, actor, operation, request_id)
      );
      CREATE TABLE admin_audit_logs (
        id text PRIMARY KEY, actor_type text NOT NULL, actor_id text, action text NOT NULL, resource_type text NOT NULL,
        resource_id text, request_id text NOT NULL, ip_address text, user_agent text, before jsonb, after jsonb,
        metadata jsonb DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX admin_audit_logs_request_action_uidx ON admin_audit_logs (request_id, action, resource_type, resource_id);
      INSERT INTO users (id) VALUES (9007199254740993), (9007199254740994), (9007199254740995);
      INSERT INTO user_sessions (id,user_id,name,editor_state_json) VALUES
        ('owned-session',9007199254740993,'old','{}'), ('foreign-session',9007199254740994,'foreign','{}');
      INSERT INTO user_preferences (user_id,meta_prompt,first_login_completed,system_config_json)
        VALUES (9007199254740993,'before',0,'{"preserved":true}');
    `);
    const role = `local_import_data_${suffix}`, rolePassword = `rp_${randomBytes(24).toString("base64url")}`;
    assert.match(role, /^[a-z0-9_]+$/); assert.match(rolePassword, /^[A-Za-z0-9_-]+$/);
    await setup.query(`
      CREATE ROLE ${role} LOGIN PASSWORD '${rolePassword}';
      GRANT USAGE ON SCHEMA public,dream TO ${role};
      GRANT SELECT,INSERT,UPDATE ON user_sessions,user_preferences TO ${role};
      GRANT INSERT ON daily_pictures,analysis_reports TO ${role};
      GRANT SELECT,INSERT ON dream.operation_receipts TO ${role};
      GRANT INSERT ON admin_audit_logs TO ${role};
      GRANT USAGE,SELECT ON SEQUENCE daily_pictures_id_seq,analysis_reports_id_seq TO ${role};
    `);
    const limitedUrl = new URL(embedded.connectionString); limitedUrl.username = role; limitedUrl.password = rolePassword;
    pool = new pg.Pool({ connectionString: limitedUrl.toString(), max: 8 });
    assert.equal((await pool.query("SELECT current_user AS role")).rows[0].role, role);
    const db = drizzle(pool), owner = "9007199254740993", service = "dream-service", subject = "oauth-subject";
    const input: LocalDataImportInput = localDataImportInputDto.parse({
      sessions: [{ id: "owned-session", name: "updated", editor_state: '{"counter":9007199254740993,"float":1.0}' }],
      pictures: [{ date: "2026-09-15", image_base64: "data:image/png;base64,AA==", prompt: "prompt" }],
      preferences: { voice_configs: '{"voice":1.0}', meta_prompt: "meta", state_config: '{"state":2}', selected_state: "focused" },
      reports: [{ type: "patterns", data: '{"counter":9007199254740993,"float":1.0}', all_notes: "notes", timestamp: "2025-09-15T05:20:00.123Z" }],
    });
    const execute = (requestId: string, value: LocalDataImportInput) => db.transaction(async tx => new ReceiptRepository(tx, service, subject).execute(
      "local-data.import", requestId, value, localDataImportOutputDto,
      async () => ({ success: true, imported: await new LocalDataImportRepository(tx, owner).importData(value) }),
    ));
    const first = await execute("import-original", input);
    assert.deepEqual(first, { success: true, imported: { sessions: 1, pictures: 1, preferences: 4, reports: 1 } });
    const imported = await setup.query(`
      SELECT
        (SELECT json_build_object('name',name,'state',editor_state_json) FROM user_sessions WHERE id='owned-session') AS session,
        (SELECT count(*)::int FROM daily_pictures WHERE user_id=9007199254740993) AS pictures,
        (SELECT json_build_object('voice',voice_configs_json,'meta',meta_prompt,'state',state_config_json,'selected',selected_state,'system',system_config_json) FROM user_preferences WHERE user_id=9007199254740993) AS preferences,
        (SELECT json_build_object('data',report_data_json,'created',to_char(created_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) FROM analysis_reports WHERE user_id=9007199254740993) AS report,
        (SELECT count(*)::int FROM dream.operation_receipts) AS receipts,
        (SELECT count(*)::int FROM admin_audit_logs) AS audits
    `);
    assert.deepEqual(imported.rows[0], {
      session: { name: "updated", state: input.sessions[0].editor_state }, pictures: 1,
      preferences: { voice: input.preferences!.voice_configs, meta: "meta", state: input.preferences!.state_config, selected: "focused", system: '{"preserved":true}' },
      report: { data: input.reports[0].data, created: input.reports[0].timestamp }, receipts: 1, audits: 1,
    });

    assert.deepEqual(await execute("import-original", input), first);
    await expectFailure(() => execute("import-original", { ...input, pictures: [] }), "OPERATION_REQUEST_CONFLICT");
    const concurrentInput = localDataImportInputDto.parse({ sessions: [], pictures: [{ date: "2026-09-16", image_base64: "image", prompt: null }], preferences: null, reports: [] });
    assert.deepEqual(await Promise.all([execute("import-concurrent", concurrentInput), execute("import-concurrent", concurrentInput)]), [
      { success: true, imported: { sessions: 0, pictures: 1, preferences: 0, reports: 0 } },
      { success: true, imported: { sessions: 0, pictures: 1, preferences: 0, reports: 0 } },
    ]);

    const beforeForeign = await setup.query("SELECT (SELECT count(*) FROM daily_pictures) AS pictures,(SELECT count(*) FROM analysis_reports) AS reports,(SELECT count(*) FROM dream.operation_receipts) AS receipts,(SELECT count(*) FROM admin_audit_logs) AS audits");
    const foreign = localDataImportInputDto.parse({
      sessions: [{ id: "new-before-conflict", name: null, editor_state: "{}" }, { id: "foreign-session", name: "takeover", editor_state: "{}" }],
      pictures: [{ date: "2026-09-17", image_base64: "image", prompt: null }], preferences: { voice_configs: null, meta_prompt: "must rollback", state_config: null, selected_state: null },
      reports: [{ type: "patterns", data: "{}", all_notes: "rollback", timestamp: "2026-09-15T00:00:00Z" }],
    });
    await expectFailure(() => execute("import-foreign", foreign), "LOCAL_DATA_SESSION_OWNER_CONFLICT");
    const afterForeign = await setup.query("SELECT (SELECT count(*) FROM daily_pictures) AS pictures,(SELECT count(*) FROM analysis_reports) AS reports,(SELECT count(*) FROM dream.operation_receipts) AS receipts,(SELECT count(*) FROM admin_audit_logs) AS audits");
    assert.deepEqual(afterForeign.rows, beforeForeign.rows);
    assert.equal((await setup.query("SELECT count(*)::int AS count FROM user_sessions WHERE id='new-before-conflict'")).rows[0].count, 0);

    const rollbackInput = localDataImportInputDto.parse({ sessions: [{ id: "fault-session", name: null, editor_state: "{}" }], pictures: [{ date: "2026-09-18", image_base64: "image", prompt: null }], preferences: null, reports: [] });
    await expectFailure(() => db.transaction(async tx => {
      await new LocalDataImportRepository(tx, owner).importData(rollbackInput);
      throw new Error("owned fault after aggregate writes");
    }));
    assert.equal((await setup.query("SELECT count(*)::int AS count FROM user_sessions WHERE id='fault-session'")).rows[0].count, 0);
    assert.equal((await setup.query("SELECT count(*)::int AS count FROM daily_pictures WHERE date='2026-09-18'")).rows[0].count, 0);

    const invalidTimestamp = { ...input, reports: [{ ...input.reports[0], timestamp: "1757913600123" }] };
    assert.equal(localDataImportInputDto.safeParse(invalidTimestamp).success, false);
    const beforeInvalid = await setup.query("SELECT count(*)::int AS count FROM analysis_reports");
    await expectFailure(() => db.transaction(async tx => {
      const parsed = localDataImportInputDto.parse(invalidTimestamp);
      await new LocalDataImportRepository(tx, owner).importData(parsed);
    }));
    assert.deepEqual((await setup.query("SELECT count(*)::int AS count FROM analysis_reports")).rows, beforeInvalid.rows);

    const unknownInput = localDataImportInputDto.parse({ sessions: [], pictures: [], preferences: null, reports: [{ type: "echoes", data: "{}", all_notes: "unknown", timestamp: "2026-09-15T00:00:00Z" }] });
    let responseLost = false;
    try { await execute("import-unknown", unknownInput); throw new Error("response lost after commit"); } catch (error) { responseLost = error instanceof Error && error.message === "response lost after commit"; }
    assert(responseLost);
    const recovered = await db.transaction(tx => new ReceiptRepository(tx, service, subject).find("local-data.import", "import-unknown"));
    assert.deepEqual(recovered?.result, { success: true, imported: { sessions: 0, pictures: 0, preferences: 0, reports: 1 } });
    assert.equal((await setup.query("SELECT count(*)::int AS count FROM analysis_reports WHERE all_notes_text='unknown'")).rows[0].count, 1);

    const complete = (canonicalUserId: string, requestId: string) => db.transaction(async tx => new ReceiptRepository(tx, service, `${subject}:${canonicalUserId}`).execute(
      "first-login.complete", requestId, {}, firstLoginCompleteOutputDto,
      async () => ({ success: true, first_login_completed: await new LocalDataImportRepository(tx, canonicalUserId).completeFirstLogin() }),
    ));
    assert.deepEqual(await complete("9007199254740995", "complete-missing"), { success: true, first_login_completed: 1 });
    const missingAfterInsert = await setup.query("SELECT first_login_completed,updated_at::text FROM user_preferences WHERE user_id=9007199254740995");
    assert.deepEqual(await complete("9007199254740995", "complete-missing"), { success: true, first_login_completed: 1 });
    assert.deepEqual((await setup.query("SELECT first_login_completed,updated_at::text FROM user_preferences WHERE user_id=9007199254740995")).rows, missingAfterInsert.rows);
    assert.deepEqual(await complete(owner, "complete-existing"), { success: true, first_login_completed: 1 });
    const existingAfterUpdate = await setup.query("SELECT first_login_completed,updated_at::text FROM user_preferences WHERE user_id=9007199254740993");
    assert.deepEqual(await complete(owner, "complete-existing"), { success: true, first_login_completed: 1 });
    assert.deepEqual((await setup.query("SELECT first_login_completed,updated_at::text FROM user_preferences WHERE user_id=9007199254740993")).rows, existingAfterUpdate.rows);
    const completion = await setup.query("SELECT user_id::text,first_login_completed,system_config_json FROM user_preferences WHERE user_id IN (9007199254740993,9007199254740995) ORDER BY user_id");
    assert.deepEqual(completion.rows, [
      { user_id: owner, first_login_completed: 1, system_config_json: '{"preserved":true}' },
      { user_id: "9007199254740995", first_login_completed: 1, system_config_json: null },
    ]);
    const totals = await setup.query("SELECT (SELECT count(*)::int FROM daily_pictures) AS pictures,(SELECT count(*)::int FROM analysis_reports) AS reports,(SELECT count(*)::int FROM dream.operation_receipts) AS receipts,(SELECT count(*)::int FROM admin_audit_logs) AS audits");
    evidence = {
      result: "PASS", target: "runner-owned-named-disposable-postgresql", database_prefix: "ink_auth_data_codex_test_local_import_",
      listen_addresses: topology.rows[0].listen, server_address: topology.rows[0].address,
      same_owner_upsert: true, foreign_owner_full_rollback: true, uow_fault_full_rollback: true,
      restricted_data_role: true,
      duplicate_replay: true, changed_input_conflict: true, concurrent_duplicate_single_effect: true,
      unknown_commit_receipt_only_recovery: true, raw_json_and_report_timestamp_round_trip: true,
      invalid_timestamp_no_effect: true, first_login_insert_update_repeat_receipt: true, totals: totals.rows[0],
    };
  } finally {
    await pool?.end(); await setup.end();
  }
} finally {
  await embedded?.stop().catch(() => undefined); await rm(ownedRoot, { recursive: true, force: true });
}

if (!evidence) throw new Error("Local-data import evidence was not produced");
console.log(JSON.stringify({ ...evidence, owned_cluster_removed: true }));
