// [Input] Runner-owned loopback PostgreSQL, Registry103 PictureHistoryRepository and strict read DTOs.
// [Output] Owner-isolated range/full projections, closed selectors, capability/scope/delegation gates and cleanup evidence.
// [Pos] Provider-free current-user picture-history contract; it never connects to configured application databases.
// [Sync] 2026-09-15: verify inclusive date filters, legacy image fallback and newest same-date full reads.
import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { AuthBoundaryError } from "../../app/lib/auth/config";
import type { DataTransaction } from "../../app/lib/dream/database";
import { withDataTransaction } from "../../app/lib/dream/database";
import { pgTimestampToIso } from "../../app/lib/dream/chatThreadDto";
import {
  pictureHistoryFullInputDto,
  pictureHistoryListInputDto,
  pictureHistoryOperationContracts,
} from "../../app/lib/dream/pictureHistoryDto";
import {
  pictureHistorySchemaRequirements,
  runPictureHistoryOperation,
} from "../../app/lib/dream/pictureHistoryService";

async function availablePort(): Promise<number> {
  const server = createServer();
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("Unable to reserve isolated port");
  await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
  return address.port;
}

async function expectAuthFailure(action: () => Promise<unknown>, code: string, status: number): Promise<void> {
  let caught: unknown;
  try { await action(); } catch (error) { caught = error; }
  assert(caught instanceof AuthBoundaryError);
  assert.equal(caught.code, code);
  assert.equal(caught.status, status);
}

const suffix = randomBytes(6).toString("hex");
const database = `ink_auth_data_codex_test_picture_history_${suffix}`;
const ownedRoot = await mkdtemp(join(tmpdir(), "ink-auth-data-picture-history-"));
let embedded: { connectionString: string; stop(): Promise<void> } | undefined;
let pool: pg.Pool | undefined;
let evidence: Record<string, unknown> | undefined;

try {
  const { startEmbeddedPostgres } = await import("../../packages/db/src/embedded-postgres");
  embedded = await startEmbeddedPostgres({
    mode: "embedded-postgres",
    dataDir: join(ownedRoot, "postgres"),
    port: await availablePort(),
    user: "postgres",
    password: `pg_${randomBytes(24).toString("base64url")}`,
    database,
    sharedBuffers: "24MB",
    maxConnections: 12,
  }, { listenAddresses: "127.0.0.1" });

  const setup = new pg.Client({ connectionString: embedded.connectionString });
  await setup.connect();
  try {
    await setup.query(`
      REVOKE CREATE ON SCHEMA public FROM PUBLIC;
      CREATE SCHEMA drizzle;
      REVOKE ALL ON SCHEMA drizzle FROM PUBLIC;
      CREATE TABLE drizzle.schema_capabilities (
        capability text PRIMARY KEY,
        version integer NOT NULL,
        contract_sha256 text NOT NULL
      );
      CREATE TABLE daily_pictures (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id bigint NOT NULL,
        date text NOT NULL,
        image_base64 text NOT NULL,
        prompt text,
        thumbnail_base64 text,
        created_at timestamptz
      );
      REVOKE ALL ON daily_pictures FROM PUBLIC;
      REVOKE ALL ON drizzle.schema_capabilities FROM PUBLIC;
    `);
    const topology = await setup.query(
      "SELECT current_database() AS database, host(inet_server_addr()) AS address, current_setting('listen_addresses') AS listen",
    );
    assert.deepEqual(topology.rows[0], { database, address: "127.0.0.1", listen: "127.0.0.1" });

    const rows = [
      ["9007199254740993", "2026-01-01", "full-old", null, null, "2026-01-01T01:00:00Z"],
      ["9007199254740993", "2026-01-02", "full-mid", "mid", "thumb-mid", "2026-01-02T01:00:00Z"],
      ["9007199254740993", "2026-01-03", "full-older", null, null, "2026-01-03T01:00:00Z"],
      ["9007199254740993", "2026-01-03", "full-newest", "latest", "thumb-newest", "2026-01-03T02:00:00Z"],
      ["9007199254740993", "2026-01-04", "full-null-time", null, null, null],
      ["9007199254740994", "2026-01-03", "other-user", "other", "other-thumb", "2026-01-03T03:00:00Z"],
    ] as const;
    for (const row of rows) {
      await setup.query(
        "INSERT INTO daily_pictures (user_id,date,image_base64,prompt,thumbnail_base64,created_at) VALUES ($1,$2,$3,$4,$5,$6)",
        row,
      );
    }

    const role = `picture_history_data_${suffix}`;
    const rolePassword = `rp_${randomBytes(24).toString("base64url")}`;
    await setup.query("CREATE ROLE " + role + " LOGIN PASSWORD '" + rolePassword + "'");
    await setup.query("GRANT USAGE ON SCHEMA public, drizzle TO " + role);
    await setup.query("GRANT SELECT ON daily_pictures, drizzle.schema_capabilities TO " + role);
    const privilege = await setup.query(`
      SELECT
        has_schema_privilege($1, 'public', 'USAGE') AS public_usage,
        has_schema_privilege($1, 'public', 'CREATE') AS public_create,
        has_schema_privilege($1, 'drizzle', 'USAGE') AS drizzle_usage,
        has_table_privilege($1, 'public.daily_pictures', 'SELECT') AS picture_select,
        has_table_privilege($1, 'public.daily_pictures', 'INSERT') AS picture_insert,
        has_table_privilege($1, 'public.daily_pictures', 'UPDATE') AS picture_update,
        has_table_privilege($1, 'public.daily_pictures', 'DELETE') AS picture_delete,
        has_table_privilege($1, 'drizzle.schema_capabilities', 'SELECT') AS capability_select
    `, [role]);
    assert.deepEqual(privilege.rows[0], {
      public_usage: true, public_create: false, drizzle_usage: true,
      picture_select: true, picture_insert: false, picture_update: false, picture_delete: false,
      capability_select: true,
    });

    const limitedUrl = new URL(embedded.connectionString);
    limitedUrl.username = role;
    limitedUrl.password = rolePassword;
    pool = new pg.Pool({ connectionString: limitedUrl.toString(), max: 4 });
    const db = drizzle(pool);
    assert.equal((await pool.query("SELECT current_user AS role")).rows[0].role, role);

    const owner = "9007199254740993";
    const other = "9007199254740994";
    const actor = (canonicalUserId: string, scopes = ["dream:read"], threadScope: string | null = null) => ({
      principal: { subject: "picture-history-subject", canonical_user_id: canonicalUserId, client_id: "dream-browser", scopes, status: "active" as const },
      threadScope,
    });
    const ownerActor = actor(owner);
    const execute = (operation: "picture-history.list" | "picture-history.full", input: unknown, currentActor = ownerActor) =>
      withDataTransaction(pictureHistorySchemaRequirements, tx => runPictureHistoryOperation(operation, input, currentActor, tx), db);
    const expected = [
      { date: "2026-01-04", base64: "full-null-time", prompt: null, created_at: null },
      { date: "2026-01-03", base64: "thumb-newest", prompt: "latest", created_at: pgTimestampToIso("2026-01-03 10:00:00+08:00") },
      { date: "2026-01-03", base64: "full-older", prompt: null, created_at: pgTimestampToIso("2026-01-03 09:00:00+08:00") },
      { date: "2026-01-02", base64: "thumb-mid", prompt: "mid", created_at: pgTimestampToIso("2026-01-02 09:00:00+08:00") },
      { date: "2026-01-01", base64: "full-old", prompt: null, created_at: pgTimestampToIso("2026-01-01 09:00:00+08:00") },
    ];

    await expectAuthFailure(
      () => execute("picture-history.list", { start_date: null, end_date: null, limit: 10 }),
      "DREAM_DATA_SCHEMA_NOT_READY",
      503,
    );
    await setup.query("INSERT INTO drizzle.schema_capabilities (capability,version,contract_sha256) VALUES ($1,$2,$3)", [
      pictureHistorySchemaRequirements[0].capability,
      pictureHistorySchemaRequirements[0].version,
      pictureHistorySchemaRequirements[0].contractSha256,
    ]);

    assert.deepEqual(await execute("picture-history.list", { start_date: null, end_date: null, limit: 10 }), { pictures: expected });
    assert.deepEqual((await execute("picture-history.list", { start_date: null, end_date: null, limit: 0 })), { pictures: [] });
    assert.deepEqual((await execute("picture-history.list", { start_date: "2026-01-02", end_date: null, limit: 10 })).pictures.map(item => item.date), ["2026-01-04", "2026-01-03", "2026-01-03", "2026-01-02"]);
    assert.deepEqual((await execute("picture-history.list", { start_date: null, end_date: "2026-01-02", limit: 10 })).pictures.map(item => item.date), ["2026-01-02", "2026-01-01"]);
    assert.deepEqual((await execute("picture-history.list", { start_date: "2026-01-02", end_date: "2026-01-03", limit: 10 })).pictures.map(item => item.date), ["2026-01-03", "2026-01-03", "2026-01-02"]);
    assert.deepEqual((await execute("picture-history.list", { start_date: null, end_date: null, limit: 2 })).pictures, expected.slice(0, 2));
    assert.deepEqual(await execute("picture-history.full", { date: "2026-01-03" }), { image_base64: "full-newest" });
    assert.deepEqual(await execute("picture-history.full", { date: "2026-02-01" }), { image_base64: null });
    assert.deepEqual((await execute("picture-history.list", { start_date: null, end_date: null, limit: 10 }, actor(other))).pictures, [{ date: "2026-01-03", base64: "other-thumb", prompt: "other", created_at: pgTimestampToIso("2026-01-03 11:00:00+08:00") }]);

    const listInput = { start_date: null, end_date: null, limit: 10 };
    const fullInput = { date: "2026-01-03" };
    for (const key of ["user_id", "actor_id", "friend_id", "table", "column", "sql", "scope", "delegation", "capability"]) {
      assert.equal(pictureHistoryListInputDto.safeParse({ ...listInput, [key]: "external" }).success, false, `list rejects ${key}`);
      assert.equal(pictureHistoryFullInputDto.safeParse({ ...fullInput, [key]: "external" }).success, false, `full rejects ${key}`);
    }
    assert.equal(pictureHistoryListInputDto.safeParse({ start_date: "2026-02-30", end_date: null, limit: 10 }).success, false);
    assert.equal(pictureHistoryFullInputDto.safeParse({ date: "not-a-date" }).success, false);
    await expectAuthFailure(() => execute("picture-history.list", { start_date: "2026-02-30", end_date: null, limit: 10 }), "INPUT_INVALID", 400);
    await expectAuthFailure(() => execute("picture-history.list", listInput, actor(owner, [])), "DREAM_SCOPE_REQUIRED", 403);
    await expectAuthFailure(() => execute("picture-history.list", listInput, actor(owner, ["dream:read"], "thread-1")), "DREAM_DELEGATION_ENTITY_DENIED", 403);

    assert.deepEqual(Object.keys(pictureHistoryOperationContracts).sort(), ["picture-history.full", "picture-history.list"]);
    assert.equal(pictureHistorySchemaRequirements.length, 1);
    assert.equal(pictureHistorySchemaRequirements[0].capability, "dream.schema.unified.v1");
    assert.equal((await pool.query("SELECT count(*)::int AS count FROM daily_pictures")).rows[0].count, 6);
    evidence = {
      result: "PASS",
      target: "runner-owned-named-disposable-postgresql",
      database_prefix: "ink_auth_data_codex_test_picture_history_",
      listen_addresses: topology.rows[0].listen,
      server_address: topology.rows[0].address,
      restricted_data_role: true,
      owner_isolation: true,
      filters_inclusive: true,
      zero_limit: true,
      thumbnail_fallback: true,
      duplicate_date_order: true,
      newest_same_date_full: true,
      nullable_prompt_and_timestamp: true,
      invalid_date_rejected_before_db: true,
      closed_selectors: true,
      missing_scope_entity_capability_fail_closed: true,
      operation_count: Object.keys(pictureHistoryOperationContracts).length,
    };
  } finally {
    await pool?.end();
    await setup.end();
  }
} finally {
  await embedded?.stop().catch(() => undefined);
  await rm(ownedRoot, { recursive: true, force: true });
}

if (!evidence) throw new Error("Picture-history evidence was not produced");
console.log(JSON.stringify({ ...evidence, owned_cluster_removed: true }));
