// [Input] Raw Python numeric lexemes, Unicode keys and real complete aggregate facts.
// [Output] Exact canonical/hash/diff assertions at the actual Node/Python helper boundary.
// [Pos] Provider-free local deterministic tests; no DB, account or external provider.
// [Sync] 2026-09-14: exercise the production bridge instead of a mirrored serializer implementation.
import {afterEach,describe,it,expect,vi} from "vitest";
import {createHash} from "node:crypto";
import {analyzeDeckSnapshot,canonicalMemory,canonicalBusinessJson,analyzeConfirmationEnvelope,compareConfirmationClaims} from "./deckContentCanonical";
afterEach(()=>vi.unstubAllEnvs());
describe("exact Python v1 serializer",()=>{
 it("preserves numeric categories and codepoint sorting through the actual bridge",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");const right='{"😀":9007199254740993,"\\ue000":-0.0,"float":1.0,"small":1e-7}';const v=await canonicalMemory(null,right);const expected='{"float":1.0,"small":1e-07,"\\ue000":-0.0,"😀":9007199254740993}';expect(v.canonical_json).toBe(expected.replace('\\ue000','\ue000'));expect(v.equal).toBe(false);expect((await canonicalMemory(right,right)).equal).toBe(true);});
 it("produces legacy fields/hash and readonly diff with raw memory JSON",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");const facts={schema_version:"deck-content/v1",deck:{id:"deck",name:"中文",name_zh:null,name_en:null,description:null,description_zh:null,description_en:null,icon:null,color:null,enabled:true,order_index:0},agent_type:"chat",agents:[{id:"voice",name:"voice",name_zh:null,name_en:null,system_prompt:"",icon:null,color:null,enabled:true,order_index:0,memory_workspace_config_json:'{"value":1.0,"integer":9007199254740993}'}],claude_plugins:[],runtime_binding:null};const v=await analyzeDeckSnapshot(facts,null);expect(v.canonical_json).toContain('"value":1.0');expect(v.canonical_json).toContain('9007199254740993');expect(v.content_hash).toBe('sha256:'+createHash('sha256').update(v.canonical_json).digest('hex'));expect(v.changes.map(c=>c.scope)).toEqual(["deck","agent_type","agents"]);expect(v.no_changes).toBe(false);const same=await analyzeDeckSnapshot(facts,v.canonical_json);expect(same.no_changes).toBe(true);expect(same.changes).toEqual([]);});
 it("shared business provenance keeps the original raw numeric hash",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");const result=await canonicalBusinessJson('{"float":1.0,"big":9007199254740993,"zero":-0.0}');expect(result.canonical_json).toBe('{"big":9007199254740993,"float":1.0,"zero":-0.0}');expect(result.content_hash).toBe("sha256:"+createHash("sha256").update(result.canonical_json).digest("hex"));});
 it.each(['{"value":NaN}','{"value":Infinity}','{"value":-Infinity}'])("strict business provenance rejects non-finite JSON %s",async raw=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");await expect(canonicalBusinessJson(raw)).rejects.toMatchObject({code:"DECK_CANONICAL_UNAVAILABLE"});});
 it("confirmation codec retains numeric command bytes and deterministic identity",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");const command='{"storyWorkspaceRunId":"run","threadId":"thread","idempotencyKey":"key","value":1.0,"big":9007199254740993}';const parts=JSON.stringify([{type:"text",text:'{"kind":"story-workspace-dream-confirmation","command":'+command+'}'}]);const result=await analyzeConfirmationEnvelope(parts,"9007199254740993");expect(result.status).toBe("valid");if(result.status!=="valid")throw new Error("Valid confirmation expected");expect(result.command_json).toContain('"value":1.0');expect(result.command_json).toContain('9007199254740993');expect(result.command_fingerprint).toBe('sha256:'+createHash('sha256').update('{"actor":"9007199254740993","command":'+result.command_json+'}').digest('hex'));expect(result.message_id).toBe('dream_confirm_'+createHash('sha256').update('{"actor":"9007199254740993","idempotencyKey":"key","storyWorkspaceRunId":"run"}').digest('hex'));});
 it.each(["not-json","[]","[{},{}]",'[{"type":"text","text":"[]"}]','[{"type":"image","text":"{}"}]',JSON.stringify([{type:"text",text:'{"kind":"story-workspace-dream-confirmation","command":{"storyWorkspaceRunId":"run","threadId":"thread","idempotencyKey":"key","value":NaN}}'}])])("malformed confirmation is a business invalid result %s",async raw=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");expect(await analyzeConfirmationEnvelope(raw,"actor")).toEqual({status:"invalid"});});
 it("claim equality ignores only lease and preserves Python numeric equality",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");expect(await compareConfirmationClaims('{"actor":"actor","value":1.0,"dispatch_claim_lease_until":200}','{"actor":"actor","value":1,"dispatch_claim_lease_until":100}')).toEqual({equal:true});expect(await compareConfirmationClaims('{"actor":"actor","value":1}','{"actor":"other","value":1}')).toEqual({equal:false});expect(await compareConfirmationClaims('[]','{}')).toEqual({equal:false});});
 it("missing deadline fails closed before spawn",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","");await expect(canonicalMemory(null,"{}")).rejects.toMatchObject({code:"AUTH_NOT_CONFIGURED"});});
});
