// [Input] Verified canonical actor, strict domain policy/input DTOs and caller-owned Drizzle transaction.
// [Output] Owner/public filtered Deck/Voice aggregates, atomic refs/forks/updates and immutable CAS versions.
// [Pos] Admin database repository; Runtime, artifact verification, shared filesystem and HTTP stay outside.
// [Sync] 2026-09-15: exact canonical text, ordered cross-Deck locks and shared owner-lock reuse for refs/memory.
import { randomUUID } from "node:crypto";
import { and, asc, desc, eq, getTableColumns, inArray, max, notInArray, or, sql } from "drizzle-orm";
import { users } from "@ink-memory/db/schema";
import { decks, voices, chat_thread, deck_versions, deck_claude_plugin_refs as refs, claude_plugin_installations as installations, deck_plugin_bindings as bindings, deck_plugin_releases as releases, deck_runtime_snapshots } from "@ink-memory/db/schema/dream";
import { z } from "zod";
import type { PgUpdateSetSource } from "drizzle-orm/pg-core";
import { AuthBoundaryError } from "../auth/config";
import { decimalIdDto } from "../auth/dto";
import type { DataTransaction } from "./database";
import * as dto from "./deckVoiceDto";
import { pgTimestampToIso } from "./chatThreadDto";
import { agentTypeFromManifest, stripPythonString } from "./deckPluginManifestDto";
import { analyzeDeckSnapshot, canonicalMemory } from "./deckContentCanonical";
const deckFields={...getTableColumns(decks),owner_id:sql<string|null>`${decks.owner_id}::text`};
const voiceFields={...getTableColumns(voices),owner_id:sql<string|null>`${voices.owner_id}::text`};
type DeckEntity=Omit<typeof decks.$inferSelect,"owner_id">&{owner_id:string|null};
type VoiceEntity=Omit<typeof voices.$inferSelect,"owner_id">&{owner_id:string|null};
function deckRow(row:DeckEntity){return dto.deckRowDto.parse({...row,created_at:pgTimestampToIso(row.created_at),updated_at:pgTimestampToIso(row.updated_at)});}
function voiceRow(row:VoiceEntity){const {memory_workspace_config,...fields}=row;let raw=memory_workspace_config;try{if(raw!==null)JSON.parse(raw);}catch{raw=null;}return dto.deckVoiceRowDto.parse({...fields,memory_workspace_config_json:raw,created_at:pgTimestampToIso(row.created_at),updated_at:pgTimestampToIso(row.updated_at)});}
function postgresCode(error:unknown):string|null {let current=error;for(let i=0;i<4&&current&&typeof current==="object";i++){if("code"in current&&typeof current.code==="string")return current.code;current="cause"in current?current.cause:null;}return null;}
export function deckState(row:Pick<DeckEntity,"id"|"draft_revision"|"latest_version"|"published_draft_revision">){const latest=row.latest_version||null;const dirty=latest===null||row.draft_revision!==row.published_draft_revision;return dto.deckVersionStateDto.parse({deck_id:row.id,draft_revision:row.draft_revision,latest_version:latest,published_draft_revision:row.published_draft_revision,dirty,status:latest===null?"unpublished":dirty?"draft":"published",next_version:(latest||0)+1});}
export class DeckVoiceRepository {
 readonly canonicalUserId:string;
 constructor(readonly transaction:DataTransaction,canonicalUserId:string,readonly policy:dto.DeckVoicePolicyDto){this.canonicalUserId=decimalIdDto.parse(canonicalUserId);}
 private owner(){return eq(decks.owner_id,sql`${this.canonicalUserId}::bigint`);}
 private async deck(id:string,mode:"read"|"share"|"update"="read",owned=true){const q=this.transaction.select(deckFields).from(decks).where(and(eq(decks.id,id),owned?this.owner():undefined)).limit(1);const rows=mode==="read"?await q:await q.for(mode);return rows[0]??null;}
 private async requireDeck(id:string,mode:"read"|"share"|"update"="read"){const row=await this.deck(id,mode);if(!row)throw new AuthBoundaryError("DECK_ACCESS_DENIED",404);return row;}
 async requireOwnedDeck(id:string,mode:"read"|"share"|"update"="read"){return this.requireDeck(id,mode);}
 private async allVoices(id:string){return this.transaction.select(voiceFields).from(voices).where(eq(voices.deck_id,id)).orderBy(asc(voices.order_index),asc(voices.created_at),asc(voices.id));}
 private async advance(id:string){await this.transaction.update(decks).set({draft_revision:sql`${decks.draft_revision}+1`,updated_at:sql`CURRENT_TIMESTAMP`}).where(eq(decks.id,id));}
 private defaultInitialized(row:DeckEntity,total:number){return !!row.is_system||[this.policy.default_system_deck_id,...this.policy.retired_system_deck_ids].includes(row.parent_id??"")||(row.parent_id===null&&!row.has_local_changes&&row.name===this.policy.template.name&&row.name_zh===this.policy.template.name_zh&&row.name_en===this.policy.template.name_en&&total===this.policy.template.voices.length);}
 private async decoration(row:DeckEntity,total:number){
  const revisions=await this.transaction.select({revision:max(bindings.binding_revision)}).from(bindings).where(eq(bindings.deck_id,row.id));
  const active=await this.transaction.select({id:bindings.deck_plugin_id,version:bindings.deck_plugin_version,manifest:releases.manifest_json}).from(bindings).innerJoin(releases,and(eq(releases.deck_plugin_id,bindings.deck_plugin_id),eq(releases.deck_plugin_version,bindings.deck_plugin_version))).where(and(eq(bindings.deck_id,row.id),eq(bindings.status,"active"),inArray(releases.status,["published","deprecated"]))).limit(1);
  const current=active[0];const state=deckState(row);return {agent_type:current?agentTypeFromManifest(current.manifest):"chat" as const,agent_type_revision:revisions[0]?.revision??0,deck_plugin_id:current?.id??null,deck_plugin_version:current?.version??null,can_publish:!this.defaultInitialized(row,total),publish_block_reason:this.defaultInitialized(row,total)?"default_initialized" as const:null,deck_version_capability:true as const,deck_version:state.latest_version,deck_version_dirty:state.dirty,deck_version_status:state.status,next_deck_version:state.next_version};
 }
 async list(community:boolean){
  const visibility=this.policy.retired_system_deck_ids.length?sql`(${decks.parent_id} IS NULL OR ${notInArray(decks.parent_id,this.policy.retired_system_deck_ids)} OR ${decks.has_local_changes} IS TRUE OR EXISTS(SELECT 1 FROM ${voices} AS retired_voice WHERE retired_voice.deck_id=${decks.id} AND retired_voice.has_local_changes IS TRUE))`:undefined;
  const where=community?and(or(and(eq(decks.id,this.policy.default_system_deck_id),eq(decks.is_system,true)),eq(decks.published,true)),sql`(${decks.owner_id} IS NULL OR ${decks.owner_id}<>${this.canonicalUserId}::bigint)`):and(this.owner(),visibility);
  const rows=await this.transaction.select(deckFields).from(decks).where(where).orderBy(...(community?[desc(decks.install_count),desc(decks.created_at)]:[asc(decks.order_index),asc(decks.created_at)]));
  const result=[];
  for(const row of rows){const counts=(await this.transaction.select({total:sql<number>`count(*)::int`,enabled:sql<number>`count(*) FILTER(WHERE ${voices.enabled} IS TRUE)::int`}).from(voices).where(eq(voices.deck_id,row.id)))[0];const authors=row.owner_id===null?[]:await this.transaction.select({name:users.display_name}).from(users).where(eq(users.id,sql`${row.owner_id}::bigint`)).limit(1);result.push(dto.deckListItemDto.parse({...deckRow(row),...await this.decoration(row,community?counts.enabled:counts.total),voice_count:counts.enabled,total_voice_count:community?null:counts.total,author_display_name:community?authors[0]?.name??null:null}));}
  return result;
 }
 async detail(id:string){const row=await this.deck(id,"share");if(!row)return null;const agents=await this.allVoices(id);return dto.deckDetailDto.parse({...deckRow(row),...await this.decoration(row,agents.length),voices:agents.map(voiceRow)});}
 private async defaultRef(id:string,evidence:z.infer<typeof dto.deckDefaultPluginEvidenceDto>){
  if(evidence.package_name!==this.policy.default_plugin_package_name||evidence.resolved_version!==this.policy.default_plugin_version)throw new AuthBoundaryError("DEFAULT_DECK_PLUGIN_UNAVAILABLE",409);
  const rows=await this.transaction.select({id:installations.id,package:installations.package_name,marketplace:installations.marketplace,version:installations.resolved_version,digest:installations.artifact_digest,status:installations.status}).from(installations).where(eq(installations.id,evidence.plugin_installation_id)).limit(1).for("share");
  const found=rows[0];if(!found||found.status!=="ready"||found.package!==evidence.package_name||found.version!==evidence.resolved_version||found.digest!==evidence.artifact_digest)throw new AuthBoundaryError("DEFAULT_DECK_PLUGIN_UNAVAILABLE",409);
  const values={deck_id:id,plugin_installation_id:found.id,package_spec:`${found.package}@${found.marketplace}`,resolved_version:found.version,artifact_digest:found.digest,enabled:1,order_index:0};
  await this.transaction.insert(refs).values(values).onConflictDoUpdate({target:[refs.deck_id,refs.plugin_installation_id],set:{package_spec:values.package_spec,resolved_version:values.resolved_version,artifact_digest:values.artifact_digest,enabled:1,updated_at:sql`CURRENT_TIMESTAMP`}});
 }
 async create(input:z.infer<typeof dto.deckCreateInputDto>){const {default_plugin_evidence,order_index,...fields}=input;const highest=(await this.transaction.select({value:max(decks.order_index)}).from(decks).where(this.owner()))[0]?.value;const id=randomUUID();await this.transaction.insert(decks).values({id,...fields,order_index:order_index??(highest||0)+1,owner_id:sql`${this.canonicalUserId}::bigint`,is_system:false,enabled:true,has_local_changes:false});await this.defaultRef(id,default_plugin_evidence);return{id};}
 async update(input:dto.DeckUpdateInputDto){const row=await this.deck(input.deck_id,"update");if(!row)return false;const changes:PgUpdateSetSource<typeof decks>={};const content=["name","name_zh","name_en","description","description_zh","description_en","icon","color"];
  for(const key of Object.keys(input.updates) as Array<keyof typeof input.updates>){const value=input.updates[key];if(value===undefined||(key==="enabled"?!!row[key]:row[key])===value)continue;Object.assign(changes,{[key]:value});}
  if(Object.keys(changes).length===0)return true;if(Object.keys(changes).some(key=>content.includes(key)))changes.has_local_changes=true;changes.updated_at=sql`CURRENT_TIMESTAMP`;await this.transaction.update(decks).set(changes).where(eq(decks.id,row.id));await this.advance(row.id);return true;
 }
 async delete(id:string){if(!await this.deck(id,"update"))return false;
  for(const [reason,q] of [["child_decks",this.transaction.select({id:decks.id}).from(decks).where(eq(decks.parent_id,id)).limit(1)],["related_threads",this.transaction.select({id:chat_thread.id}).from(chat_thread).where(eq(chat_thread.deck_id,id)).limit(1)],["runtime_history",this.transaction.select({id:deck_runtime_snapshots.deck_runtime_snapshot_id}).from(deck_runtime_snapshots).where(eq(deck_runtime_snapshots.deck_id,id)).limit(1)]] as const){if((await q).length)throw new AuthBoundaryError("DECK_DELETE_BLOCKED",409,{reason});}
  try{await this.transaction.delete(refs).where(eq(refs.deck_id,id));await this.transaction.delete(bindings).where(eq(bindings.deck_id,id));await this.transaction.delete(decks).where(eq(decks.id,id));}catch(e){if(postgresCode(e)==="23503")throw new AuthBoundaryError("DECK_DELETE_BLOCKED",409,{reason:"referenced_records"});throw e;}return true;
 }
 async togglePublication(id:string){const row=await this.requireDeck(id,"update");if(row.published){await this.transaction.update(decks).set({published:false,updated_at:sql`CURRENT_TIMESTAMP`}).where(eq(decks.id,id));return false;}const agents=await this.allVoices(id);if(this.defaultInitialized(row,agents.length))throw new AuthBoundaryError("DEFAULT_DECK_PUBLISH_FORBIDDEN",409);const author=(await this.transaction.select({name:users.display_name}).from(users).where(eq(users.id,sql`${this.canonicalUserId}::bigint`)).limit(1))[0]?.name||`User ${this.canonicalUserId}`;await this.transaction.update(decks).set({published:true,author_name:author,parent_id:null,updated_at:sql`CURRENT_TIMESTAMP`}).where(eq(decks.id,id));return true;}
 private collectable(row:DeckEntity){if(row.owner_id===this.canonicalUserId)throw new AuthBoundaryError("SELF_COLLECTION_FORBIDDEN",409);if(!row.is_system&&!row.published)throw new AuthBoundaryError("COLLECTION_SOURCE_UNAVAILABLE",404);}
 private async copyVoices(source:string,target:string){const agents=await this.allVoices(source);for(const row of agents){await this.transaction.insert(voices).values({id:randomUUID(),deck_id:target,name:row.name,name_zh:row.name_zh,name_en:row.name_en,system_prompt:row.system_prompt,icon:row.icon,color:row.color,is_system:false,parent_id:row.id,owner_id:sql`${this.canonicalUserId}::bigint`,enabled:true,has_local_changes:false,order_index:row.order_index,memory_workspace_config:row.memory_workspace_config||this.policy.default_memory_workspace_config_json});}return agents.length;}
 private async fork(row:DeckEntity,evidence:z.infer<typeof dto.deckDefaultPluginEvidenceDto>|null=null){const id=randomUUID();await this.transaction.insert(decks).values({id,name:row.name,name_zh:row.name_zh,name_en:row.name_en,description:row.description,description_zh:row.description_zh,description_en:row.description_en,icon:row.icon,color:row.color,is_system:false,parent_id:row.id,owner_id:sql`${this.canonicalUserId}::bigint`,enabled:true,has_local_changes:false,order_index:row.order_index});await this.copyVoices(row.id,id);const sourceRefs=await this.transaction.select().from(refs).where(eq(refs.deck_id,row.id));for(const {created_at:created,updated_at:updated,...ref}of sourceRefs){void created;void updated;await this.transaction.insert(refs).values({...ref,deck_id:id});}if(evidence)await this.defaultRef(id,evidence);return id;}
 async collect(id:string){const row=await this.deck(id,"update",false);if(!row)throw new AuthBoundaryError("DECK_ACCESS_DENIED",404);this.collectable(row);const created=await this.fork(row);await this.transaction.update(decks).set({install_count:sql`${decks.install_count}+1`}).where(eq(decks.id,id));return created;}
 async syncParent(id:string){const row=await this.requireDeck(id,"update");if(!row.parent_id)throw new AuthBoundaryError("DECK_PARENT_MISSING",409);const parent=await this.deck(row.parent_id,"share",false);if(!parent)throw new AuthBoundaryError("DECK_PARENT_MISSING",404);const {name,name_zh,name_en,description,description_zh,description_en,icon,color}=parent;await this.transaction.update(decks).set({name,name_zh,name_en,description,description_zh,description_en,icon,color,has_local_changes:false,updated_at:sql`CURRENT_TIMESTAMP`}).where(eq(decks.id,id));await this.transaction.delete(voices).where(eq(voices.deck_id,id));const count=await this.copyVoices(parent.id,id);await this.advance(id);return {success:true as const,synced_voices:count};}
 private async defaultTemplate(evidence:z.infer<typeof dto.deckDefaultPluginEvidenceDto>){const {voices:roles,...template}=this.policy.template;const {id}=await this.create({...template,order_index:null,default_plugin_evidence:evidence});for(const [order,role]of roles.entries()){await this.transaction.insert(voices).values({id:randomUUID(),deck_id:id,...role,owner_id:sql`${this.canonicalUserId}::bigint`,is_system:false,enabled:true,has_local_changes:false,order_index:order,memory_workspace_config:this.policy.default_memory_workspace_config_json});}return id;}
 private async defaultActorLock(){await this.transaction.execute(sql`SELECT pg_advisory_xact_lock(hashtextextended(${`deck-default:${this.canonicalUserId}`},0))`);}
 async provisionDefault(evidence:z.infer<typeof dto.deckDefaultPluginEvidenceDto>){await this.defaultActorLock();const source=await this.deck(this.policy.default_system_deck_id,"share",false);return source?.is_system?this.fork(source,evidence):this.defaultTemplate(evidence);}
 async reconcileDefault(evidence:z.infer<typeof dto.deckDefaultPluginEvidenceDto>){await this.defaultActorLock();const owned=await this.transaction.select(deckFields).from(decks).where(and(this.owner(),eq(decks.is_system,false),eq(decks.has_local_changes,false))).orderBy(asc(decks.created_at));let found:DeckEntity|undefined;
  for(const candidate of owned){const row=await this.deck(candidate.id,"update");if(!row||row.is_system!==false||row.has_local_changes!==false)continue;if(row.parent_id===this.policy.default_system_deck_id){found=row;break;}if(row.parent_id!==null)continue;const agents=await this.allVoices(row.id);if(this.defaultInitialized(row,agents.length)&&agents.every(a=>!a.has_local_changes&&this.policy.template.voices.some(r=>r.name===(a.name_zh??a.name)))){found=row;break;}}
  if(!found)return{deck_id:await this.defaultTemplate(evidence),reconciled:true,reason:"default_created" as const};await this.requireDeck(found.id,"update");if((await this.transaction.select({id:refs.plugin_installation_id}).from(refs).where(eq(refs.deck_id,found.id)).limit(1)).length)return{deck_id:found.id,reconciled:false,reason:"refs_preserved" as const};await this.defaultRef(found.id,evidence);await this.advance(found.id);return{deck_id:found.id,reconciled:true,reason:"missing_ref" as const};
 }
 async createVoice(input:z.infer<typeof dto.voiceCreateInputDto>){await this.requireDeck(input.deck_id,"update");const highest=(await this.transaction.select({value:max(voices.order_index)}).from(voices).where(eq(voices.deck_id,input.deck_id)))[0]?.value;const {memory_workspace_config_json,order_index,...fields}=input;const raw=memory_workspace_config_json;const empty=raw!==null&&Object.keys(JSON.parse(raw)).length===0;const id=randomUUID();await this.transaction.insert(voices).values({id,...fields,owner_id:sql`${this.canonicalUserId}::bigint`,is_system:false,enabled:true,has_local_changes:false,order_index:order_index??(highest||0)+1,memory_workspace_config:raw===null||empty?this.policy.default_memory_workspace_config_json:raw});await this.advance(input.deck_id);return id;}
 private async ownedVoice(id:string){const target=(await this.transaction.select({deck:voices.deck_id}).from(voices).where(and(eq(voices.id,id),eq(voices.owner_id,sql`${this.canonicalUserId}::bigint`))).limit(1))[0];if(!target)return null;if(!await this.deck(target.deck,"update"))return null;return(await this.transaction.select(voiceFields).from(voices).where(and(eq(voices.id,id),eq(voices.owner_id,sql`${this.canonicalUserId}::bigint`))).limit(1).for("update"))[0]??null;}
 async updateVoice(input:dto.VoiceUpdateInputDto){const row=await this.ownedVoice(input.voice_id);if(!row)return false;const changes:PgUpdateSetSource<typeof voices>={};const content=["name","name_zh","name_en","system_prompt","icon","color"];
  for(const key of Object.keys(input.updates) as Array<keyof typeof input.updates>){const value=input.updates[key];if(value===undefined)continue;if(key==="memory_workspace_config_json"){const memory=await canonicalMemory(row.memory_workspace_config,input.updates.memory_workspace_config_json??null);if(!memory.equal)changes.memory_workspace_config=value===null?null:memory.canonical_json;continue;}if((key==="enabled"?!!row[key]:row[key])!==value)Object.assign(changes,{[key]:value});}
  if(Object.keys(changes).length===0)return true;if(typeof changes.thread_id==="string"){const target=await this.transaction.select({id:chat_thread.id}).from(chat_thread).where(and(eq(chat_thread.id,changes.thread_id),eq(chat_thread.user_id,sql`${this.canonicalUserId}::bigint`))).limit(1);if(!target.length)throw new AuthBoundaryError("CHAT_THREAD_NOT_FOUND",404);}
  if(Object.keys(changes).some(key=>content.includes(key)))changes.has_local_changes=true;changes.updated_at=sql`CURRENT_TIMESTAMP`;await this.transaction.update(voices).set(changes).where(eq(voices.id,row.id));if(Object.keys(changes).some(key=>key!=="thread_id"&&key!=="updated_at"))await this.advance(row.deck_id);return true;
 }
 async deleteVoice(id:string){const row=await this.ownedVoice(id);if(!row)return false;try{await this.transaction.delete(voices).where(eq(voices.id,id));}catch(e){if(postgresCode(e)==="23503")throw new AuthBoundaryError("VOICE_REFERENCED",409);throw e;}await this.advance(row.deck_id);return true;}
 async collectVoice(id:string,target:string){
  if(!await this.deck(target))throw new AuthBoundaryError("DECK_ACCESS_DENIED",404);
  const first=(await this.transaction.select({deck_id:voices.deck_id}).from(voices).where(eq(voices.id,id)).limit(1))[0];
  if(!first)throw new AuthBoundaryError("VOICE_ACCESS_DENIED",404);
  const allowedSource=await this.deck(first.deck_id,"read",false);
  if(!allowedSource||allowedSource.owner_id!==this.canonicalUserId&&!allowedSource.is_system&&!allowedSource.published)throw new AuthBoundaryError("VOICE_ACCESS_DENIED",404);
  // Two users may collect each other's public Voice simultaneously. Acquire
  // both Deck locks in the same key order before re-reading all permission facts.
  const locked=await this.transaction.select(deckFields).from(decks).where(inArray(decks.id,[target,first.deck_id])).orderBy(asc(decks.id)).for("update");
  const targetDeck=locked.find(row=>row.id===target),sourceDeck=locked.find(row=>row.id===first.deck_id);
  if(!targetDeck||targetDeck.owner_id!==this.canonicalUserId)throw new AuthBoundaryError("DECK_ACCESS_DENIED",404);
  if(!sourceDeck||sourceDeck.owner_id!==this.canonicalUserId&&!sourceDeck.is_system&&!sourceDeck.published)throw new AuthBoundaryError("VOICE_ACCESS_DENIED",404);
  const source=(await this.transaction.select(voiceFields).from(voices).where(and(eq(voices.id,id),eq(voices.deck_id,sourceDeck.id))).limit(1).for("share"))[0];
  if(!source)throw new AuthBoundaryError("VOICE_ACCESS_DENIED",404);
  const highest=(await this.transaction.select({value:max(voices.order_index)}).from(voices).where(eq(voices.deck_id,target)))[0]?.value;
  const created=randomUUID();await this.transaction.insert(voices).values({id:created,deck_id:target,name:source.name,name_zh:source.name_zh,name_en:source.name_en,system_prompt:source.system_prompt,icon:source.icon,color:source.color,is_system:false,parent_id:source.id,owner_id:sql`${this.canonicalUserId}::bigint`,enabled:true,order_index:(highest||0)+1,memory_workspace_config:source.memory_workspace_config||this.policy.default_memory_workspace_config_json});await this.advance(target);return created;
 }
 async state(id:string){return deckState(await this.requireDeck(id));}
 private async snapshot(row:DeckEntity){const agents=await this.allVoices(row.id);const selected=await this.transaction.select().from(refs).where(eq(refs.deck_id,row.id)).orderBy(asc(refs.order_index),asc(refs.plugin_installation_id));const active=(await this.transaction.select({id:bindings.deck_plugin_id,version:bindings.deck_plugin_version,revision:bindings.binding_revision,manifest:releases.manifest_json}).from(bindings).innerJoin(releases,and(eq(releases.deck_plugin_id,bindings.deck_plugin_id),eq(releases.deck_plugin_version,bindings.deck_plugin_version))).where(and(eq(bindings.deck_id,row.id),eq(bindings.status,"active"))).orderBy(desc(bindings.binding_revision)).limit(1))[0];const {id,name,name_zh,name_en,description,description_zh,description_en,icon,color,enabled,order_index}=row;return{schema_version:"deck-content/v1",deck:{id,name,name_zh,name_en,description,description_zh,description_en,icon,color,enabled,order_index},agent_type:active?agentTypeFromManifest(active.manifest):"chat",agents:agents.map(a=>({id:a.id,name:a.name,name_zh:a.name_zh,name_en:a.name_en,system_prompt:a.system_prompt,icon:a.icon,color:a.color,enabled:!!a.enabled,order_index:a.order_index,memory_workspace_config_json:a.memory_workspace_config})),claude_plugins:selected.map(ref=>({plugin_installation_id:ref.plugin_installation_id,package_spec:ref.package_spec,resolved_version:ref.resolved_version,artifact_digest:ref.artifact_digest,enabled:!!ref.enabled,order_index:ref.order_index})),runtime_binding:active?{deck_plugin_id:active.id,deck_plugin_version:active.version,binding_revision:active.revision}:null};}
 private conflict(state:dto.DeckVersionStateDto){return new AuthBoundaryError("DECK_VERSION_CONFLICT",409,{current_draft_revision:state.draft_revision,current_version:state.latest_version});}
 private async analysis(input:z.infer<typeof dto.deckVersionMutationInputDto>,lock:"share"|"update"){const row=await this.requireDeck(input.deck_id,lock);const state=deckState(row);if(state.draft_revision!==input.expected_draft_revision||state.latest_version!==input.expected_base_version)throw this.conflict(state);let base:string|null=null;if(state.latest_version!==null){const selected=(await this.transaction.select({raw:sql<string>`COALESCE(${deck_versions.snapshot_canonical_json},${deck_versions.snapshot_json}::text)`}).from(deck_versions).where(and(eq(deck_versions.deck_id,row.id),eq(deck_versions.version,state.latest_version))).limit(1))[0];if(!selected)throw this.conflict({...state,draft_revision:1});base=selected.raw;}const result=await analyzeDeckSnapshot(await this.snapshot(row),base);if(result.no_changes)throw new AuthBoundaryError("DECK_VERSION_NO_CHANGES",409);return{row,state,result};}
 async preview(input:z.infer<typeof dto.deckVersionMutationInputDto>){const {state,result}=await this.analysis(input,"share");return dto.deckVersionPreviewDto.parse({...state,target_version:state.next_version,changes:result.changes,impact:["新建 Thread/新运行可以选择该最新 Deck 版本。","历史 Thread 不会自动升级。","当前草稿在提交成功后与新版本一致。"]});}
 private summaryFields(){return{version:deck_versions.version,base_version:deck_versions.base_version,source_draft_revision:deck_versions.source_draft_revision,description:deck_versions.description,content_hash:deck_versions.content_hash,created_by:sql<string>`${deck_versions.created_by}::text`,created_at:deck_versions.created_at,runtime_plugin_version:sql<string|null>`${deck_versions.snapshot_json}->'runtime_binding'->>'deck_plugin_version'`};}
 private summary(row:Awaited<ReturnType<DeckVoiceRepository["versionRows"]>>[number]){return dto.deckVersionSummaryDto.parse({...row,created_at:pgTimestampToIso(row.created_at)});}
 private async versionRows(id:string,limit:number){return this.transaction.select(this.summaryFields()).from(deck_versions).where(eq(deck_versions.deck_id,id)).orderBy(desc(deck_versions.version)).limit(limit);}
 async commit(input:z.infer<typeof dto.deckVersionCommitInputDto>){const {row,state,result}=await this.analysis(input,"update");const inserted=(await this.transaction.insert(deck_versions).values({id:`dcv_${randomUUID().replaceAll("-","")}`,deck_id:row.id,version:state.next_version,base_version:state.latest_version,source_draft_revision:state.draft_revision,description:input.description?stripPythonString(input.description):null,snapshot_json:sql`${result.canonical_json}::jsonb`,snapshot_canonical_json:result.canonical_json,content_hash:result.content_hash,created_by:sql`${this.canonicalUserId}::bigint`}).returning(this.summaryFields()))[0];await this.transaction.update(decks).set({latest_version:state.next_version,published_draft_revision:state.draft_revision,updated_at:sql`CURRENT_TIMESTAMP`}).where(eq(decks.id,row.id));return dto.deckVersionCommitDto.parse({deck_id:row.id,version:this.summary(inserted),state:deckState({...row,latest_version:state.next_version,published_draft_revision:state.draft_revision})});}
 async history(input:z.infer<typeof dto.deckVersionHistoryInputDto>){const state=await this.state(input.deck_id);return dto.deckVersionHistoryDto.parse({deck_id:input.deck_id,current:state,versions:(await this.versionRows(input.deck_id,input.limit)).map(row=>this.summary(row))});}
 async version(input:z.infer<typeof dto.deckVersionDetailInputDto>){await this.requireDeck(input.deck_id);const row=(await this.transaction.select({...this.summaryFields(),snapshot_json:sql<string>`COALESCE(${deck_versions.snapshot_canonical_json},${deck_versions.snapshot_json}::text)`}).from(deck_versions).where(and(eq(deck_versions.deck_id,input.deck_id),eq(deck_versions.version,input.version))).limit(1))[0];if(!row)throw new AuthBoundaryError("DECK_VERSION_NOT_FOUND",404);const {snapshot_json,...summary}=row;return dto.deckVersionDetailDto.parse({...this.summary(summary),deck_id:input.deck_id,snapshot_json});}
}
