// [Input] Explicit existing Dream source/Python harness and original full manifest/numeric/snapshot fixtures.
// [Output] Source-model/default/coercion validation plus production legacy hash/diff equality.
// [Pos] Cross-project provider-free integration, excluded from ordinary single-repo unit runs.
// [Sync] 2026-09-15: verify model Unicode White_Space and explicit Python capability blank checks; no duplicated state machine, DB, external providers or real-user data.
import {spawnSync} from "node:child_process";
import {resolve} from "node:path";
import {afterEach,describe,it,expect,vi} from "vitest";
import {deckPluginManifestDto} from "./deckPluginManifestDto";
import {analyzeDeckSnapshot,canonicalMemory,analyzeConfirmationEnvelope} from "./deckContentCanonical";
const fixture={schema_version:"deck-plugin/v1",deck_plugin_id:"example.story",deck_plugin_version:"1.0.0",display_name:"Story",description:"Story plugin",author:"Fixture",status:"published",workflow:{workflow_definition_ref:"workflow",input_schema_ref:"input",output_schema_ref:"output",steps:[{step_id:"start"}]},compatibility:{deck_host_api:"*",claude_agent_contract:"*",claude_code:"*",story_output_schema:"*",deck_runtime_snapshot_contract:"*"},runtime_configuration:{profile_contract:"profile/v1",required_config_keys:[],secret_ref_kinds:[],allow_profile_versions:"*"},capabilities:["story.workspace.propose"],runtime:{claude_code_plugins:[]},dependencies:{}};
function oracle(input:unknown){const binary=process.env.INK_DREAM_PYTHON,source=process.env.INK_DREAM_SOURCE;if(!binary||!source)throw new Error("Explicit cross-project Python/source harness required");const r=spawnSync(binary,["-I",resolve("tests/integration/deckLegacyOracle.py")],{input:JSON.stringify(input),encoding:"utf8",env:{PATH:process.env.PATH,INK_DREAM_SOURCE:source} as unknown as NodeJS.ProcessEnv});if(r.status!==0)throw new Error("Original source oracle failed: "+r.status+" "+r.stderr);return JSON.parse(r.stdout);}
afterEach(()=>vi.unstubAllEnvs());
describe("actual legacy Dream parity",()=>{
 it("confirmation fingerprint and identity match actual original source",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");const command='{ "storyWorkspaceRunId":"run","threadId":"thread","idempotencyKey":"key","float":1.0,"big":9007199254740993 }';const raw=JSON.stringify([{type:"text",text:'{"kind":"story-workspace-dream-confirmation","command":'+command+'}'}]);const actual=await analyzeConfirmationEnvelope(raw,"9007199254740993");expect(actual.status).toBe("valid");if(actual.status!=="valid")throw new Error("Valid confirmation required");const expected=oracle({action:"confirmation",actor:"9007199254740993",command_json:command});expect(actual.command_fingerprint).toBe(expected.command_fingerprint);expect(actual.message_id).toBe(expected.message_id);});
 it("matches complete original Python manifest acceptance/defaults/coercion",()=>{const cases:unknown[]=[fixture,{},null,{capabilities:["story.workspace.propose"]},{...fixture,schema_version:" deck-plugin/v1 "},{...fixture,status:" published "},{...fixture,deck_plugin_id:" example.story "},{...fixture,deck_plugin_id:"\u0085example.story\u0085"},{...fixture,deck_plugin_id:"\ufeffexample.story\ufeff"},{...fixture,capabilities:["story.workspace.propose"," story.workspace.propose "]},{...fixture,workflow:{...fixture.workflow,steps:[{step_id:" start ",required_capabilities:["  "]}]}},{...fixture,runtime:{claude_code_plugins:[{claude_code_plugin_id:"cli",source_ref:"source",version_constraint:"*",required:"yes"}]}},{...fixture,deck_plugin_version:"1٢.0.0"},{...fixture,dependencies:{extra:1}},{...fixture,compatibility:{...fixture.compatibility,claude_code:0}},{...fixture,capabilities:["\u0085story.workspace.propose\u0085"]}];for(const value of ["\u001c","\u001d","\u001e","\u001f"]){cases.push({...fixture,description:value+"text"+value},{...fixture,deck_plugin_id:value+"example.story"+value},{...fixture,capabilities:[value]},{...fixture,capabilities:[value+"story.workspace.propose"+value]});}for(const value of ["\u0085","\u00a0","\u1680","\u2000","\u200a","\u2028","\u2029","\u202f","\u205f","\u3000"]){cases.push({...fixture,display_name:value+"Story"+value});}const expected=oracle({action:"manifest",cases});for(const [i,input]of cases.entries()){const actual=deckPluginManifestDto.safeParse(input);expect(actual.success,`case ${i}`).toBe(expected[i].accepted);if(actual.success)expect(actual.data,`normalization ${i}`).toEqual(expected[i].value);}});
 it("matches original canonical bytes for raw floats/bigints/Unicode/escaping",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");const cases=['{"value":1.0}','{"value":-0.0}','{"value":1e-7}','{"value":1e16}','{"value":9007199254740993}','{"value":1234567890123456789012345678901234567890}','{"😀":1,"\\ue000":2}','{"value":"中文\\n\\t\\\\\\\""}','{"value":[1,1.0,-0.0,1e-5,1e20]}'];const expected=oracle({action:"canonical",cases});for(const [i,raw]of cases.entries())expect((await canonicalMemory(null,raw)).canonical_json,`case ${i}`).toBe(expected[i].canonical_json);});
 it("matches original DB-facts snapshot/hash/diff rather than a copied builder",async()=>{vi.stubEnv("DREAM_DOMAIN_CANONICAL_TIMEOUT_MS","5000");const deck={id:"deck",name:"中文",name_zh:null,name_en:null,description:null,description_zh:null,description_en:null,icon:null,color:null,enabled:true,order_index:0};const raw='{"float":1.0,"big":9007199254740993,"zero":-0.0}';const voice={id:"voice",name:"voice",name_zh:null,name_en:null,system_prompt:"",icon:null,color:null,enabled:true,order_index:0,memory_workspace_config:raw};const {memory_workspace_config,...agent}=voice;const facts={schema_version:"deck-content/v1",deck,agent_type:"chat",agents:[{...agent,memory_workspace_config_json:memory_workspace_config}],claude_plugins:[],runtime_binding:null};const first=await analyzeDeckSnapshot(facts,null);const expected=oracle({action:"snapshot",deck,voices:[voice],refs:[],binding:[],base_json:null});expect(first.canonical_json).toBe(expected.canonical_json);expect(first.content_hash).toBe(expected.content_hash);expect(first.changes).toEqual(expected.changes);const nextFacts={...facts,deck:{...deck,name:"下一版"}};const next=await analyzeDeckSnapshot(nextFacts,first.canonical_json);const nextExpected=oracle({action:"snapshot",deck:nextFacts.deck,voices:[voice],refs:[],binding:[],base_json:first.canonical_json});expect(next.canonical_json).toBe(nextExpected.canonical_json);expect(next.content_hash).toBe(nextExpected.content_hash);expect(next.changes).toEqual(nextExpected.changes);});
});
