// [Input] Strict public social DTOs and typed service seams without SQL/provider execution.
// [Output] Owner/scope/policy/precision/closed-error and pair-key regression evidence.
// [Pos] Focused domain tests; Drizzle concurrency/receipt assertions live in the public isolated harness.
// [Sync] 2026-09-15: preserve product error shapes and exact identities while excluding external acting IDs.
import { afterEach, describe, expect, it, vi } from "vitest";
import type { DataTransaction } from "./database";
import type { ChatThreadActor } from "./chatThreadService";
import { SocialFriendshipRepository, friendshipPairKey, generateFriendInviteCode } from "./socialFriendshipRepository";
import { runSocialFriendshipOperation, configuredSocialFriendshipPolicy } from "./socialFriendshipService";
import { socialFriendshipOperationContracts as contracts, socialFriendshipPolicyDto, socialDecisionResultDto } from "./socialFriendshipDto";
const tx = {} as DataTransaction;
const actor: ChatThreadActor = { principal: { subject: "social-subject", canonical_user_id: "9007199254740993", client_id: "dream-browser", scopes: ["dream:read", "dream:write"], status: "active" }, threadScope: null };
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllEnvs(); });
describe("social strict DTO and pair lock identity", () => {
  it.each(["user_id", "actor_id", "table", "sql", "scope", "expires_at"])("rejects caller-authored %s", key => { expect(contracts["friend-invite.generate"].input.safeParse({ [key]: "external" }).success).toBe(false); expect(contracts["friend-invite.use"].input.safeParse({ code: "ABC123", [key]: "external" }).success).toBe(false); });
  it("preserves original exact code and date without normalization", () => { expect(contracts["friend-invite.use"].input.parse({ code: " abc " })).toEqual({ code: " abc " }); expect(contracts["friendship.picture-full"].input.parse({ friend_id: "9223372036854775807", date: "legacy-date" }).date).toBe("legacy-date"); });
  it.each(["0", "01", "-1", "9223372036854775808"])("rejects invalid bigint selector %s", id => { expect(contracts["friend-request.accept"].input.safeParse({ request_id: id }).success).toBe(false); });
  it("uses numeric ordering for one reciprocal exact pair key", () => { expect(friendshipPairKey("10", "2")).toBe("dream.friendship:2:10"); expect(friendshipPairKey("9007199254740993", "9223372036854775807")).toBe(friendshipPairKey("9223372036854775807", "9007199254740993")); });
  it("accepts original product failures only", () => { expect(socialDecisionResultDto.parse({ success: false, error: "Permission denied" })).toEqual({ success: false, error: "Permission denied" }); expect(socialDecisionResultDto.safeParse({ success: false, error: "raw provider or SQL error" }).success).toBe(false); });
  it("allows zero timeline items and rejects negative/unsafe limits", () => { expect(contracts["friendship.timeline"].input.safeParse({ friend_id: "2", limit: 0 }).success).toBe(true); expect(contracts["friendship.timeline"].input.safeParse({ friend_id: "2", limit: -1 }).success).toBe(false); expect(contracts["friendship.timeline"].input.safeParse({ friend_id: "2", limit: Number.MAX_SAFE_INTEGER + 1 }).success).toBe(false); });
});
describe("social server policy and owner service", () => {
  it("requires explicit valid server policy", () => { vi.stubEnv("DREAM_FRIENDSHIP_POLICY_JSON", ""); expect(configuredSocialFriendshipPolicy).toThrowError("FRIENDSHIP_POLICY_NOT_CONFIGURED"); vi.stubEnv("DREAM_FRIENDSHIP_POLICY_JSON", '{"code_length":6,"lifetime_seconds":604800,"generation_attempts":64}'); expect(configuredSocialFriendshipPolicy()).toEqual({ code_length: 6, lifetime_seconds: 604800, generation_attempts: 64 }); expect(socialFriendshipPolicyDto.safeParse({ code_length: 0, lifetime_seconds: 604800, generation_attempts: 64 }).success).toBe(false); });
  it("does not require generation config for ordinary reads", async () => { vi.stubEnv("DREAM_FRIENDSHIP_POLICY_JSON", ""); vi.spyOn(SocialFriendshipRepository.prototype, "friends").mockResolvedValue({ friends: [] }); expect(await runSocialFriendshipOperation("friendship.list", {}, actor, tx)).toEqual({ friends: [] }); });
  it("generates the configured original alphabet without ambient random", () => { expect(generateFriendInviteCode(6)).toMatch(/^[A-Z0-9]{6}$/); });
  it("keeps generation policy server-owned and exact expiry", async () => { const generate = vi.spyOn(SocialFriendshipRepository.prototype, "generate").mockResolvedValue({ code: "ABC123", expires_at: "2026-09-22T12:34:56.123456+08:00" }); const policy = { code_length: 6, lifetime_seconds: 604800, generation_attempts: 64 }; expect(await runSocialFriendshipOperation("friend-invite.generate", {}, actor, tx, policy)).toEqual({ code: "ABC123", expires_at: "2026-09-22T12:34:56.123456+08:00" }); expect(generate).toHaveBeenCalledWith(policy); });
  it("preserves approved bigint and label result", async () => { const result = { success: true as const, friend_request_id: "9007199254740995", inviter_id: "9007199254740997", inviter_name: "用户" }; vi.spyOn(SocialFriendshipRepository.prototype, "use").mockResolvedValue(result); expect(await runSocialFriendshipOperation("friend-invite.use", { code: "ABC123" }, actor, tx)).toEqual(result); });
  it("keeps original recipient decision error", async () => { vi.spyOn(SocialFriendshipRepository.prototype, "decide").mockResolvedValue({ success: false, error: "Request already rejected" }); expect(await runSocialFriendshipOperation("friend-request.accept", { request_id: "2" }, actor, tx)).toEqual({ success: false, error: "Request already rejected" }); });
  it("retains nullable historical times and thumbnail/prompt fields", async () => { const result = { pictures: [{ date: "2026-09-15", base64: "thumbnail", prompt: null, created_at: null }, { date: "2026-09-14", base64: "full", prompt: "", created_at: "2026-09-14T01:02:03.000001+08:00" }] }; vi.spyOn(SocialFriendshipRepository.prototype, "timeline").mockResolvedValue(result); expect(await runSocialFriendshipOperation("friendship.timeline", { friend_id: "2", limit: 30 }, actor, tx)).toEqual(result); });
  it("returns null for inaccessible friend pictures", async () => { vi.spyOn(SocialFriendshipRepository.prototype, "picture").mockResolvedValue({ image_base64: null }); expect(await runSocialFriendshipOperation("friendship.picture-full", { friend_id: "2", date: "2026-09-15" }, actor, tx)).toEqual({ image_base64: null }); });
  it("rejects inadequate scope before persistence", async () => { const use = vi.spyOn(SocialFriendshipRepository.prototype, "use"); await expect(runSocialFriendshipOperation("friend-invite.use", { code: "ABC123" }, { ...actor, principal: { ...actor.principal, scopes: ["dream:read"] } }, tx)).rejects.toMatchObject({ code: "DREAM_SCOPE_REQUIRED", status: 403 }); expect(use).not.toHaveBeenCalled(); });
  it("rejects entity delegation before persistence", async () => { const friends = vi.spyOn(SocialFriendshipRepository.prototype, "friends"); await expect(runSocialFriendshipOperation("friendship.list", {}, { ...actor, threadScope: "unrelated-thread" }, tx)).rejects.toMatchObject({ code: "DREAM_DELEGATION_ENTITY_DENIED", status: 403 }); expect(friends).not.toHaveBeenCalled(); });
  it("rejects corrupt database projection rather than returning extra fields", async () => { vi.spyOn(SocialFriendshipRepository.prototype, "friends").mockResolvedValue({ friends: [{ friend_id: "2", display_name: "wrong shape" }] } as never); await expect(runSocialFriendshipOperation("friendship.list", {}, actor, tx)).rejects.toThrow(); });
});
