// [Input] Closed SystemConfig DTO/service, original typed repository and mandatory codec seams.
// [Output] OAuth/entity/strict field/precision/failure/order assertions without SQL or provider.
// [Pos] Candidate checks; concurrency, receipt and public behavior require later registered contracts.
// [Sync] 2026-09-15: preserve raw old keys and immutable server-owned Runtime configuration.
import { afterEach, describe, expect, it, vi } from "vitest";
import type { DataTransaction } from "./database";
import { UserSystemConfigRepository } from "./userSystemConfigRepository";
import { runUserSystemConfigOperation, type UserSystemConfigActor } from "./userSystemConfigService";
import { userSystemConfigPatchDto } from "./userSystemConfigDto";
const actor: UserSystemConfigActor = { principal: { subject: "config-subject", canonical_user_id: "9007199254740993", client_id: "browser", scopes: ["dream:read", "dream:write"], status: "active" }, threadScope: null, runScope: null, editorSessionScope: null };
const tx = {} as DataTransaction;
afterEach(() => vi.restoreAllMocks());
describe("closed normalized SystemConfig", () => {
  it.each(["user_id", "actor_id", "sql", "table", "system_config_json", "arbitrary_key"])("rejects %s", key => expect(userSystemConfigPatchDto.safeParse({ [key]: "caller" }).success).toBe(false));
  it("preserves original model pair and Python codepoint prompt", () => expect(userSystemConfigPatchDto.parse({ model: "platform:model-1", provider: "gateway", system_prompt: "😀".repeat(16384) })).toEqual({ model: "platform:model-1", provider: "gateway", system_prompt: "😀".repeat(16384) }));
  it("rejects unpaired model/provider", () => { expect(userSystemConfigPatchDto.safeParse({ model: "model" }).success).toBe(false); expect(userSystemConfigPatchDto.safeParse({ provider: "gateway" }).success).toBe(false); });
  it.each(["API_KEY", "INK_AGENT_SANDBOX_ENABLED", "CLAUDE_CODE_EFFORT_LEVEL", "CLAUDE_CODE_TMPDIR", "INK_CLAUDE_CODE_MODEL_MAX_OUTPUT_TOKENS"])("rejects protected env %s", key => expect(userSystemConfigPatchDto.safeParse({ env_vars: { [key]: "caller" } }).success).toBe(false));
  it("accepts normalized ordinary env and sandbox rules", () => expect(userSystemConfigPatchDto.safeParse({ env_vars: { LANG: "zh_CN.UTF-8" }, sandbox_network_allowed_domains: ["*.example.com"], sandbox_fs_allowed_write_paths: ["/work"] }).success).toBe(true));
  it("rejects nonnormalized paths, duplicate domains and python whitespace", () => { expect(userSystemConfigPatchDto.safeParse({ sandbox_fs_allowed_write_paths: ["relative"] }).success).toBe(false); expect(userSystemConfigPatchDto.safeParse({ sandbox_network_allowed_domains: ["example.com", "example.com"] }).success).toBe(false); expect(userSystemConfigPatchDto.safeParse({ env_vars: { "\u0085LANG": "value" } }).success).toBe(false); });
});
describe("SystemConfig service", () => {
  it("returns exact raw JSON without JS number conversion", async () => { const raw = '{"large":9007199254740993,"float":1.0,"negative":-0.0,"unknown":{"文字":"Ω"}}'; vi.spyOn(UserSystemConfigRepository.prototype, "get").mockResolvedValue({ system_config_json: raw }); const codec = vi.fn().mockResolvedValue({ config_json: raw }); expect(await runUserSystemConfigOperation("user-system-config.get", {}, actor, tx, codec)).toEqual({ config_json: raw }); expect(codec).toHaveBeenCalledExactlyOnceWith({ action: "read", stored_json: raw }); });
  it("passes absence to codec instead of default on failure", async () => { vi.spyOn(UserSystemConfigRepository.prototype, "get").mockResolvedValue(null); const codec = vi.fn().mockResolvedValue({ config_json: "{}" }); expect(await runUserSystemConfigOperation("user-system-config.get", {}, actor, tx, codec)).toEqual({ config_json: "{}" }); expect(codec).toHaveBeenCalledExactlyOnceWith({ action: "read", stored_json: null }); });
  it("locks before merge and updates only the codec result", async () => { const events: string[] = [], raw = '{"old":9007199254740993}', merged = '{"old":9007199254740993,"theme":"dark"}'; vi.spyOn(UserSystemConfigRepository.prototype, "ensureLocked").mockImplementation(async () => { events.push("lock"); return { system_config_json: raw }; }); const update = vi.spyOn(UserSystemConfigRepository.prototype, "update").mockImplementation(async () => { events.push("update"); }); const codec = vi.fn().mockImplementation(async () => { events.push("codec"); return { config_json: merged }; }); expect(await runUserSystemConfigOperation("user-system-config.patch", { theme: "dark" }, actor, tx, codec)).toEqual({ success: true }); expect(events).toEqual(["lock", "codec", "update"]); expect(update).toHaveBeenCalledExactlyOnceWith(merged); expect(codec).toHaveBeenCalledExactlyOnceWith({ action: "merge", stored_json: raw, patch: { theme: "dark" } }); });
  it("fails before update when codec fails", async () => { vi.spyOn(UserSystemConfigRepository.prototype, "ensureLocked").mockResolvedValue({ system_config_json: "broken" }); const update = vi.spyOn(UserSystemConfigRepository.prototype, "update").mockResolvedValue(undefined); await expect(runUserSystemConfigOperation("user-system-config.patch", {}, actor, tx, async () => { throw new Error("codec unavailable"); })).rejects.toThrow("codec unavailable"); expect(update).not.toHaveBeenCalled(); });
  it("rejects malformed codec envelope", async () => { vi.spyOn(UserSystemConfigRepository.prototype, "get").mockResolvedValue(null); await expect(runUserSystemConfigOperation("user-system-config.get", {}, actor, tx, async () => ({ config_json: "{}", caller: true }))).rejects.toMatchObject({ code: "USER_SYSTEM_CONFIG_DATA_INVALID" }); });
  it.each(["threadScope", "runScope", "editorSessionScope"] as const)("denies entity %s for user management", async key => { const get = vi.spyOn(UserSystemConfigRepository.prototype, "get").mockResolvedValue(null); await expect(runUserSystemConfigOperation("user-system-config.get", {}, { ...actor, [key]: "entity" }, tx, async () => ({ config_json: "{}" }))).rejects.toMatchObject({ code: "DREAM_DELEGATION_ENTITY_DENIED", status: 403 }); expect(get).not.toHaveBeenCalled(); });
  it("requires read and write scopes independently", async () => { await expect(runUserSystemConfigOperation("user-system-config.patch", {}, { ...actor, principal: { ...actor.principal, scopes: ["dream:read"] } }, tx, async () => ({ config_json: "{}" }))).rejects.toMatchObject({ code: "DREAM_SCOPE_REQUIRED", status: 403 }); });
});
